name: API Automation CI

on:
  push:
    branches: [ main ]

jobs:
  compile:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: sport

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Maven Compile
        run: mvn clean compile